import { useEffect, useState } from "react";

const api = process.env.REACT_APP_API_URL || "http://localhost:5000";
const emptyDoctor = { name: "", speciality: "", gender: "Other", bio: "", image: "" };

export default function DoctorAdmin() {
  const [token, setToken] = useState(localStorage.getItem("departmentAdminToken") || "");
  const [credentials, setCredentials] = useState({ email: "", password: "" });
  const [doctors, setDoctors] = useState([]);
  const [form, setForm] = useState(emptyDoctor);
  const [image, setImage] = useState(null);
  const [editing, setEditing] = useState(null);
  const [message, setMessage] = useState("");
  const load = () => fetch(`${api}/api/doctors`).then((r) => r.ok ? r.json() : []).then(setDoctors).catch(() => setMessage("Unable to reach the backend. Start it with npm start."));
  useEffect(() => { load(); }, []);
  const login = async (event) => { event.preventDefault(); setMessage(""); try { const r = await fetch(`${api}/api/admin/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(credentials) }); const result = await r.json(); if (!r.ok) throw new Error(result.message); localStorage.setItem("departmentAdminToken", result.token); setToken(result.token); } catch (error) { setMessage(error.message || "Sign in failed."); } };
  const save = async (event) => { event.preventDefault(); setMessage(""); const data = new FormData(); Object.entries(form).forEach(([key, value]) => data.append(key, value)); if (image) data.append("image", image); try { const r = await fetch(`${api}/api/doctors${editing ? `/${editing._id}` : ""}`, { method: editing ? "PUT" : "POST", headers: { Authorization: `Bearer ${token}` }, body: data }); const result = await r.json().catch(() => ({})); if (!r.ok) throw new Error(result.message); setForm(emptyDoctor); setImage(null); setEditing(null); setMessage("Doctor saved."); load(); } catch (error) { setMessage(error.message || "Could not save doctor."); } };
  const remove = async (doctor) => { if (!window.confirm(`Remove ${doctor.name}?`)) return; const r = await fetch(`${api}/api/doctors/${doctor._id}`, { method: "DELETE", headers: { Authorization: `Bearer ${token}` } }); if (r.ok) { load(); setMessage("Doctor removed."); } else setMessage("Could not remove doctor."); };
  if (!token) return <main className="mx-auto max-w-md p-6"><h1 className="text-2xl font-bold text-[#0E5260]">Doctors admin</h1><form onSubmit={login} className="mt-6 space-y-4 rounded-xl bg-white p-6 shadow"><input required type="text" placeholder="Username" autoComplete="username" className="w-full rounded border p-3" onChange={(e) => setCredentials({ ...credentials, email: e.target.value })}/><input required type="password" placeholder="Password" autoComplete="current-password" className="w-full rounded border p-3" onChange={(e) => setCredentials({ ...credentials, password: e.target.value })}/><button className="w-full rounded bg-[#0E5260] p-3 font-semibold text-white">Sign in</button>{message && <p className="text-sm text-red-600">{message}</p>}</form></main>;
  return <main className="mx-auto max-w-5xl p-4 sm:p-8"><div className="mb-6 flex items-center justify-between"><h1 className="text-2xl font-bold text-[#0E5260]">Doctors content manager</h1><button onClick={() => { localStorage.removeItem("departmentAdminToken"); setToken(""); }} className="text-sm font-semibold text-red-700">Sign out</button></div><form onSubmit={save} className="grid gap-4 rounded-xl bg-white p-5 shadow sm:grid-cols-2"><h2 className="sm:col-span-2 text-lg font-bold">{editing ? `Edit ${editing.name}` : "Add doctor"}</h2><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Doctor name" className="rounded border p-3"/><input required value={form.speciality} onChange={(e) => setForm({ ...form, speciality: e.target.value })} placeholder="Speciality" className="rounded border p-3"/><select value={form.gender} onChange={(e) => setForm({ ...form, gender: e.target.value })} className="rounded border p-3"><option>Other</option><option>Male</option><option>Female</option></select><input value={form.image} onChange={(e) => setForm({ ...form, image: e.target.value })} placeholder="Existing image URL (optional)" className="rounded border p-3"/><div className="sm:col-span-2"><label className="block text-sm font-semibold">Profile image</label><input accept="image/*" type="file" onChange={(e) => setImage(e.target.files[0])}/></div><textarea value={form.bio} onChange={(e) => setForm({ ...form, bio: e.target.value })} placeholder="Doctor profile / description" className="min-h-28 rounded border p-3 sm:col-span-2"/><div className="flex gap-3 sm:col-span-2"><button className="rounded bg-[#0E5260] px-5 py-3 font-semibold text-white">Save doctor</button>{editing && <button type="button" onClick={() => { setEditing(null); setForm(emptyDoctor); setImage(null); }} className="rounded border px-5 py-3">Cancel</button>}</div>{message && <p className="sm:col-span-2 text-sm text-[#0E5260]">{message}</p>}</form><section className="mt-8 grid gap-3"><h2 className="text-lg font-bold">Managed doctors</h2>{doctors.length === 0 && <p className="text-slate-600">No managed doctors yet. Add doctors here; the current public list will remain visible until you save your first doctor.</p>}{doctors.map((doctor) => <article key={doctor._id} className="flex items-center justify-between rounded-lg bg-white p-4 shadow-sm"><span><b>{doctor.name}</b><br/><small>{doctor.speciality}</small></span><span className="flex gap-3"><button onClick={() => { setEditing(doctor); setForm({ name: doctor.name, speciality: doctor.speciality, gender: doctor.gender, bio: doctor.bio || "", image: doctor.image || "" }); window.scrollTo({ top: 0, behavior: "smooth" }); }} className="text-[#0E5260]">Edit</button><button onClick={() => remove(doctor)} className="text-red-700">Delete</button></span></article>)}</section></main>;
}
